---
title: "Introduction to R Course Materials"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    theme: cerulean
    toc: no
---

# Day 1: Introduction

- [Slides](01.Introduction/01.slides.html)
- Lesson Material
    - [Web-based](01.Introduction/01.guide.html)
    - [Word Document](01.Introduction/01.guide.docx)
- [Code Files](01.Introduction/code/index.html)
- [Data Files](01.Introduction/data/index.html)

Day 1 Objectives:

- Become familiar with the RStudio IDE, R syntax, and R data types
- Understand how to get help with R
- Become familiar with the R reference card
- Become familiar with Rmarkdown to generate reports



# Day 2: Graphics

- [Slides](02.Graphics/02.slides.html)
- Lesson Material
    - [Web-based](02.Graphics/02.guide.html)
    - [Word Document](02.Graphics/02.guide.docx)
- [Code Files](02.Graphics/code/index.html)
- [Data Files](02.Graphics/data/index.html)

Day 2 Objectives:

- Use `qplot` and `ggplot` to construct plots in R
- Understand how to create layered graphics
- Apply perceptual principles to create good graphics

# Day 3: Manipulating Data

- [Slides](03.DataManipulation/03.slides.html)
- Lesson Material
    - [Web-based](03.DataManipulation/03.guide.html)
    - [Word Document](03.DataManipulation/03.guide.docx)
- [Code Files](03.DataManipulation/code/index.html)
- [Data Files](03.DataManipulation/data/index.html)

Day 3 Objectives:
- Learn how to summarize data efficiently
- Understand how to convert between wide form and long form data as well as the uses for each type of data
- Recognize "tidy" data and use `tidyr` and `dplyr` functions to work towards "tidy" data
- Understand how to work with dates and times in R

# Reference Material:

## Installing R
- [Guide to Installing R, RStudio, and Database packages](InstallGuide.html)

## Learning R
- [Introduction to R Bootcamp](https://www.datacamp.com/courses/free-introduction-to-r) - Free datacamp course covering the basics of R
- [Try R](http://tryr.codeschool.com/) - Codeschool class that allows you to interactively learn R
- Computerworld Insider [Learn R Programming](http://www.computerworld.com/article/2884322/app-development/learn-r-programming-basics-with-our-pdf.html#tk.ctw-infsb) guide (free registration required)
- [swirl](http://swirlstats.com/), an R package designed to teach you R from the command line
- Using RStudio: [Webinars](https://www.rstudio.com/resources/webinars/) and Training documents
- [How to make 50 different types of visualizations in ggplot2](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
- [R Style Guide](http://adv-r.had.co.nz/Style.html) - How to organize and format R code so that it is readable and easily shared.
- [Using R with Databases](https://bigdatauniversity.com/courses/using-r-with-databases/) - A free course on using SQL and R together, connecting to databases using RODBC and RJDBC, and similar topics.

## Learning more about R and Data Science
- [R for Data Science](http://r4ds.had.co.nz/) - A book written by Hadley Wickham and Garret Grolemund (both of RStudio) which is available online for free (and is also in print). Covers most of the material in this course in great detail. 
- [R bloggers](http://www.r-bloggers.com/) contains useful information on how to use packages, announcements for new packages, and other current goings-on in the R community. 
- [RStudio Conference 2017 Webinars](https://www.rstudio.com/resources/webinars/#rstudioconf) A series of webinars introducing new topics in R and Data Science. Learn how to structure databases, how to do 'tidy' analyses with R and RStudio, how to manipulate text, and much more.

## Get Help
- [Stackoverflow](https://stackoverflow.com/questions/tagged/r) is a great place to look for solutions to problems in R. You can also post questions if there is not a similar question that has already been asked.
